

GET http://localhost:3000/api/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJBcmN0aWsxIiwidXNlcmlkIjoyfSwiaWF0IjoxNjI1MzkzOTA5fQ.4wAjjGtcEm_frsqRDYpuUb_jrRhxNUy30v3ZgUHahdc

GET http://localhost:3000/api/user/2 HTTP/1.1






POST http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
  "name": "Aecr", 
  "email": "1@1.com", 
  "main_char": "Lee", 
  "steam_profile": "", 
  "description": "", 
  "password": "qwer1234", 
  "password2": "qwer1234"
}

PUT http://localhost:3000/api/user/2 HTTP/1.1
content-type: application/json

{
  "name": "Arctik1",
  "main_char": "Lars",
  "password": "qwer1234", 
  "password2": "qwer1234"
}

POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
  "name": "Arctik1",
  "password": "qwer11234"
}


DELETE http://localhost:3000/api/user/2 HTTP/1.1